export enum MessageTypes {
    AUTH_WITH_PASSWORD = "authwithpassword",
    OAUTH = "oauth",
    ISRATELIMITED = "isRatelimited",
    ISONLINE = "ping",
    AUH_GUIDED_HANDSHAKE = "authGuidedHandshake",
    REFRESH_TOKEN = "tokenRefresh",
    FETCH_FILE = "fetchFile",
    CHECK_ONLINE = "checkStatus",
    CHANGE_PASSWORD =  "changePassword",
    LIST = "list",
    AUTH_UPDATE = "authUpdate",
    REALTIME_SUBSCRIBE = "realtime",
    REALTIME_UNSUBSCRIBE = "unsubscribe",
    DELETE = "delete",
    REQUEST_PASSWORD_RESET="requestPasswordReset",
    RESET_PASSWORD="resetPassword",
    CHECK_TOKEN="checkToken",
}