name: Formatting Validation
on:
  pull_request:
    branches: [main]
jobs:
  reformat:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # Install Node version 20 (Latest - 2023/09/15)
      # TODO: Determine if this is what will be supported long term
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      # Install packages based off package-lock.json
      - run: npm ci
      # Format with prettier
      - run: npm run format
      # Commit the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatting fixes (Prettier)
          branch: ${{ github.head_ref }}
